domain_path: /home/noah/Projects/ECE-4310_Lab-10_Vitis/ECE-4310_Lab-10_Microblaze/export/ECE-4310_Lab-10_Microblaze/sw/standalone_microblaze_I
app_src_dir: /tools/Xilinx/Vitis/2024.1/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
